[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['solmate/=lib/solmate/src/','ds-test/=lib/ds-test/src/', 'openzeppelin/=lib/openzeppelin-contracts/','openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts']
optimizer = true                                              # enable or disable the solc optimizer
optimizer_runs = 4000
verbosity = 3

# See more config options https://github.com/gakonst/foundry/tree/master/config